elastos/Elastos.Community

Elastos Deep Dive/README.md, README.md
Added newly added videos and blogs
=> Added newly added videos and blogs 

ElastosDeepDive/README.md, ElastosVirtualMeetup/README.md, README.md
Added new content in preparation for first virtual meetup
=> Added new content in preparation for first virtual meetup

ElastosBountyProgram/front-end/src/module/page/community/PublicCommunityDetail/Component.js
Addresses Issue #17 
Rewords the join community message to be grammatically correct.
=> Reword join community message

ElastosBountyProgram/back-end/src/db/schema/SubmissionSchema.ts, ElastosBountyProgram/back-end/src/router/submission/comment.ts, ElastosBountyProgram/back-end/src/router/submission/index.ts, ElastosBountyProgram/back-end/src/service/CommentService.ts, ElastosBountyProgram/back-end/src/service/SubmissionService.ts, ElastosBountyProgram/front-end/src/module/common/comments/Component.js, ElastosBountyProgram/front-end/src/module/common/comments/Container.js, ElastosBountyProgram/front-end/src/module/common/comments/style.scss, ElastosBountyProgram/front-end/src/module/page/admin/submission_detail/Component.js, ElastosBountyProgram/front-end/src/module/submission/detail/Component.js, ElastosBountyProgram/front-end/src/service/CommentService.js, ElastosBountyProgram/front-end/src/service/SubmissionService.js
Implements a standalone Comments component.
Usage:
```
<Comments type="submission" canPost={true} model={this.props.submission}/>
```
Supports posting comments, live updates, and email notifications for owner.
Wired up to Admin/Submissions/Detail and Profile/Submissions/Detail.
Container model (submission, task) agnostic, but the models which can support comments need to:
- support a /comment API
- implement the correct comments db schema
- implement the 'detail' redux pattern
=> Implement Comments component

ElastosBountyProgram/back-end/src/db/schema/CommentSchema.ts, ElastosBountyProgram/back-end/src/db/schema/SubmissionSchema.ts, ElastosBountyProgram/back-end/src/db/schema/TaskSchema.ts, ElastosBountyProgram/back-end/src/router/task/comment.ts, ElastosBountyProgram/back-end/src/router/task/index.ts, ElastosBountyProgram/back-end/src/service/TaskService.ts, ElastosBountyProgram/front-end/src/module/common/comments/Component.js, ElastosBountyProgram/front-end/src/module/common/comments/Container.js, ElastosBountyProgram/front-end/src/module/task/Component.js, ElastosBountyProgram/front-end/src/module/task/detail/Component.js
Extends the comments to tasks. Supports all task detail views.
=> Wire up comments to tasks

ElastosBountyProgram/back-end/src/db/schema/SubmissionSchema.ts, ElastosBountyProgram/back-end/src/service/SubmissionService.ts, ElastosBountyProgram/front-end/src/module/page/admin/submissions/Component.js, ElastosBountyProgram/front-end/src/module/page/developer/formSubmission/Component.js, ElastosBountyProgram/front-end/src/module/page/developer/formSubmission/Container.js, ElastosBountyProgram/front-end/src/module/page/profile/submissions/Component.js, ElastosBountyProgram/front-end/src/module/submission/detail/Component.js
=> Extend submissions with title

ElastosBountyProgram/back-end/src/service/SubmissionService.ts, ElastosBountyProgram/back-end/src/service/TaskService.ts, ElastosBountyProgram/front-end/src/module/common/comments/Component.js
Using selects to filter out hidden props on user models contained in tasks, submissions, and their comments.
=> Rework user prop sanitization

ElastosBountyProgram/back-end/src/router/user/index.ts, ElastosBountyProgram/back-end/src/router/user/send_confirm_email.ts, ElastosBountyProgram/back-end/src/router/user/send_reg_email.ts, ElastosBountyProgram/back-end/src/service/UserService.ts, ElastosBountyProgram/front-end/src/module/form/LoginForm/Container.js, ElastosBountyProgram/front-end/src/module/form/RegisterForm/Component.js, ElastosBountyProgram/front-end/src/module/form/RegisterForm/Container.js, ElastosBountyProgram/front-end/src/service/UserService.js
Quick solution. We should improve to sending out confirmation links for more security later.
=> Add email verification on register

ElastosBountyProgram/front-end/src/module/form/RegisterForm/Container.js
=> 38 - Fix registration email

ElastosBountyProgram/front-end/src/module/common/comments/Component.js, ElastosBountyProgram/front-end/src/module/form/TaskCreateForm/Component.js, ElastosBountyProgram/front-end/src/module/form/TaskCreateForm/Container.js, ElastosBountyProgram/front-end/src/module/task/Component.js
=> 53 - Properly reset the task editing form

ElastosBountyProgram/front-end/src/module/task/style.scss
The padding got removed after the merge of Task Applications.
Also affects task details.
=> Fix: Styling of task application details

ElastosBountyProgram/front-end/src/module/page/login/style.scss, ElastosBountyProgram/front-end/src/module/page/register/style.scss, ElastosBountyProgram/front-end/src/style/mobile.scss
change login style.scss and  register style.scss
=> change mobile.scss, make sure tags visiable on mobile side.

ElastosBountyProgram/back-end/src/router/task/list.ts, ElastosBountyProgram/back-end/src/service/.test/Community.spec.ts, ElastosBountyProgram/back-end/src/service/.test/Task.spec.ts, ElastosBountyProgram/back-end/src/service/.test/Task.update.spec.ts, ElastosBountyProgram/back-end/src/service/.test/Team.spec.ts, ElastosBountyProgram/back-end/src/service/.test/User.test.ts, ElastosBountyProgram/back-end/src/service/TaskService.ts, ElastosBountyProgram/back-end/src/service/UserService.ts, ElastosBountyProgram/back-end/src/utility/.test/crypto.spec.ts, ElastosBountyProgram/back-end/src/utility/.test/index.spec.ts, ElastosBountyProgram/front-end/src/module/task/detail/Component.js
1. Fixed a couple of findings from a security sweep:
- task list, admin=true coming from frontend
- show user (UserService.ts/show) is accepting admin=true from frontend, effect (right now) can potentially see peoples emails
- specific methods in services have no checks for current users permissions, to name a few, TaskService.ts/acceptCandidate, removeCandidate, addCandidate, …, CommunityService.ts/removeMember, …
- IMPORTANT: also UserService.ts/update, changePassword for example!
2. Fixed backend unit tests and implemented new ones for TaskService, UserService (increase from virtually 0% coverage).
3. Disabled the non working unit tests.
4. npm test now works, in sequential mode.
```
Test Suites: 9 passed, 9 total
Tests:       35 passed, 35 total
Snapshots:   0 total
Time: …
```
=> Improve sensitive function security and unit test framework

ElastosBountyProgram/back-end/test/unit/jest.conf.js
https://github.com/jsdom/jsdom/issues/2304
=> Fix jest build config

ElastosBountyProgram/front-end/src/module/page/developer/learn/style.scss, ElastosBountyProgram/front-end/src/module/page/profile/info/Component.js, ElastosBountyProgram/front-end/src/module/page/shared/HomeNavigator/style.scss, ElastosBountyProgram/front-end/src/module/page/shared/Navigator/Component.js
- Fixed mobile padding on learning page.
- Added horizontal scrolling for the My Republic navigation menu on mobile views.
- Adjusted profile page navigation layout.
=> Mobile tweaks

ElastosBountyProgram/back-end/src/db/schema/UserSchema.ts, ElastosBountyProgram/back-end/src/service/UserService.ts, ElastosBountyProgram/front-end/src/I18N/en.js
Reverts elastos/Elastos.Community#108
Merged into master by accident, sorry about that.
=> Revert "Tajeran/email login"

ElastosBountyProgram/back-end/src/service/UserService.ts, ElastosBountyProgram/front-end/src/module/page/admin/users/Container.js
This change simply includes email data when obtaining user data as an administrator.
=> Added email data to user admin page.

ElastosBountyProgram/back-end/src/service/UserService.ts, ElastosBountyProgram/front-end/src/I18N/en.js
Email login changes got unintentionally reverted. This commit re-adds this functionality.
=> Re-add email login

ElastosBountyProgram/front-end/src/module/form/TeamCreateForm/Component.js
transfer team 'type' attr to back-end
=> fix team edit bug

ElastosBountyProgram/back-end/src/router/user/check_email.ts, ElastosBountyProgram/back-end/src/router/user/index.ts, ElastosBountyProgram/back-end/src/service/UserService.ts, ElastosBountyProgram/front-end/src/I18N/en.js, ElastosBountyProgram/front-end/src/I18N/zh.js, ElastosBountyProgram/front-end/src/module/form/RegisterForm/Component.js, ElastosBountyProgram/front-end/src/module/form/RegisterForm/Container.js, ElastosBountyProgram/front-end/src/module/form/RegisterForm/style.scss, ElastosBountyProgram/front-end/src/service/UserService.js
add the prompt on the log in page when user fills in email which is duplicate
=> Add the prompt on the login page

ElastosBountyProgram/back-end/src/service/CommentService.ts, ElastosBountyProgram/front-end/src/module/common/comments/Component.js, ElastosBountyProgram/front-end/src/module/common/comments/Container.js, ElastosBountyProgram/front-end/src/module/page/circle_detail/application/Component.js, ElastosBountyProgram/front-end/src/module/page/circle_detail/detail/Component.js, ElastosBountyProgram/front-end/src/module/page/project_detail/application/Component.js, ElastosBountyProgram/front-end/src/module/project/application/Component.js, ElastosBountyProgram/front-end/src/module/project/detail/Component.js, ElastosBountyProgram/front-end/src/module/submission/detail/Component.js, ElastosBountyProgram/front-end/src/module/task/application/Component.js, ElastosBountyProgram/front-end/src/module/task/detail/Component.js, ElastosBountyProgram/front-end/src/module/team/application/Component.js, ElastosBountyProgram/front-end/src/module/team/detail/Component.js, ElastosBountyProgram/front-end/src/service/CommentService.js
Targeting post-release, DO NOT MERGE for now
=> Implement mentions in chat

ElastosBountyProgram/back-end/src/service/TaskService.ts
Proposal for the APPROVED+ status based handling, accompanies an ongoing offline discussion
=> Only allow bidding on approved tasks

ElastosBountyProgram/back-end/src/router/task/list.ts, ElastosBountyProgram/front-end/src/module/page/profile/tasks/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/tasks/Container.js
... and introduce Needs Approval filter
=> Show all tasks under My Tasks for admins

ElastosBountyProgram/back-end/src/router/task/list.ts, ElastosBountyProgram/front-end/src/module/page/profile/tasks/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/tasks/Container.js
and introduce Needs Approval filter
=> Hotfix: Show all tasks under My Tasks for admins 

ElastosBountyProgram/front-end/src/module/page/ProfilePage.js, ElastosBountyProgram/front-end/src/module/page/profile/communities/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/info/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/project_detail/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/projects/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/submission_create/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/submission_detail/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/submissions/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/task_candidate_detail/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/task_detail/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/tasks/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/team_create/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/team_detail/Component.js, ElastosBountyProgram/front-end/src/module/page/profile/teams/Component.js
=> Redirect to Login page when accessing /profile links when not logged in

ElastosBountyProgram/front-end/src/module/project/detail/Component.js, ElastosBountyProgram/front-end/src/module/task/popup/Component.js, ElastosBountyProgram/front-end/src/module/team/popup/Component.js
Clickable user links (Owner field) in 3 locations.
- Project detail page in my republic
- Project/Task popup in community
- Team popup in community
Removed some unused imports.
=> Add  clickable user links

ElastosBountyProgram/back-end/src/db/schema/UserSchema.ts, ElastosBountyProgram/back-end/src/router/user/login.ts, ElastosBountyProgram/back-end/src/service/UserService.ts
@ClarenceL I put the login dates into user object, please help review the code, thanks.
=> add method to record user login date
